on: pull_request

jobs:
    testbox:
      runs-on: ubuntu-latest
      container:
        image: foundeo/cfml-ci-tools:latest
      steps:  
      - uses: actions/checkout@v2
      - name: Start a server
        run: box server start cfengine=lucee@5 rewritesEnable=true saveSettings=true -Dlucee-extensions=465E1E35-2425-4F4E-8B3FAB638BD7280A,37C61C0A-5D7E-4256-8572639BE0CF5838" trayEnable=false openbrowser=false --verbose
      - name: Install dependencies
        run: box install
      - name: Run TestBox Tests
        run: box testbox run