on: pull_request

jobs:
    testbox:
      runs-on: ubuntu-latest
      # testbox uses encodeForHTML so we need that extension installed also H2 JDBC drivers
      env:
          LUCEE_EXTENSIONS: "465E1E35-2425-4F4E-8B3FAB638BD7280A;name=H2;version=1.3.172,37C61C0A-5D7E-4256-8572639BE0CF5838;name=ESAPI;version=2.1.0.18"
      container:
        image: foundeo/cfml-ci-tools:latest
      steps:  
      - uses: actions/checkout@v2
      - name: Start a server
        run: box server start cfengine=lucee@5 rewritesEnable=true saveSettings=true trayEnable=false openbrowser=false --verbose
      - name: Install dependencies
        run: box install
      - name: Run TestBox Tests
        run: box testbox run